<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS" tests="24" time="4059.630" ignored="0" failures="0" timestamp="05 Jun 2021 14:22:38 GMT" skipped="15" hostname="LAPTOP-2HJFJ1OT" errors="7">
  <testcase name="testFavouriteItems" time="272.656" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testFavouriteItems -->
  <testcase name="testFavouriteItems" time="76.931" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.stopTest(Base.java:88)
	at Resources.FunctionalComponents.validateQASite(FunctionalComponents.java:146)
	at MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS.testFavouriteItems(TestChilisIOS.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testFavouriteItems -->
  <testcase name="testCurbsideAsapOrder" time="327.589" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.stopTest(Base.java:88)
	at Resources.FunctionalComponents.clickMenuButton(FunctionalComponents.java:179)
	at MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS.testCurbsideAsapOrder(TestChilisIOS.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testCurbsideAsapOrder -->
  <testcase name="testRewardsFeature" time="212.476" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS"/>
  <testcase name="testUpdateAccountFeature" time="261.734" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testUpdateAccountFeature -->
  <testcase name="testAddMyVisit" time="114.485" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.stopTest(Base.java:88)
	at Resources.FunctionalComponents.validateQASite(FunctionalComponents.java:146)
	at MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS.testAddMyVisit(TestChilisIOS.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testAddMyVisit -->
  <testcase name="testLoggedInOrderFeature" time="115.917" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.stopTest(Base.java:88)
	at Resources.FunctionalComponents.validateQASite(FunctionalComponents.java:146)
	at MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS.testLoggedInOrderFeature(TestChilisIOS.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testLoggedInOrderFeature -->
  <testcase name="testMCACarryoutLaterToday" time="109.466" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testMCACarryoutLaterToday -->
  <testcase name="testFavouriteItems" time="152.887" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testFavouriteItems -->
  <testcase name="testCurbsideAsapOrder" time="126.351" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testCurbsideAsapOrder -->
  <testcase name="testLocationFeature" time="211.002" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS"/>
  <testcase name="testLoginFeature" time="115.097" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testLoginFeature -->
  <testcase name="testAddMyVisit" time="126.472" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testAddMyVisit -->
  <testcase name="testAddMyVisit" time="304.862" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testAddMyVisit -->
  <testcase name="testLoginFeature" time="218.623" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testLoginFeature -->
  <testcase name="testMCACarryoutLaterToday" time="226.908" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testMCACarryoutLaterToday -->
  <testcase name="testUpdateAccountFeature" time="90.111" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.stopTest(Base.java:88)
	at Resources.FunctionalComponents.validateQASite(FunctionalComponents.java:146)
	at MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS.testUpdateAccountFeature(TestChilisIOS.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testUpdateAccountFeature -->
  <testcase name="testLocationFeature" time="115.536" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testLocationFeature -->
  <testcase name="testCurbsideAsapOrder" time="76.014" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testCurbsideAsapOrder -->
  <testcase name="testLoginFeature" time="228.085" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.stopTest(Base.java:88)
	at Resources.FunctionalComponents.clickMenuButton(FunctionalComponents.java:179)
	at MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS.testLoginFeature(TestChilisIOS.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testLoginFeature -->
  <testcase name="testMCACarryoutLaterToday" time="157.458" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.stopTest(Base.java:88)
	at Resources.FunctionalComponents.validateQASite(FunctionalComponents.java:146)
	at MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS.testMCACarryoutLaterToday(TestChilisIOS.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testMCACarryoutLaterToday -->
  <testcase name="testLoggedInOrderFeature" time="220.969" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testLoggedInOrderFeature -->
  <testcase name="testLoggedInOrderFeature" time="121.812" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testLoggedInOrderFeature -->
  <testcase name="testUpdateAccountFeature" time="76.189" classname="MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS">
    <skipped/>
  </testcase> <!-- testUpdateAccountFeature -->
</testsuite> <!-- MobileAutomation.MobileSeeTestWebAutomation.TestChilisIOS -->
